import os
import oracledb
from dotenv import load_dotenv

load_dotenv()

conn = oracledb.connect(
    user=os.getenv("ORACLE_USER"),
    password=os.getenv("ORACLE_PASSWORD"),
    dsn=os.getenv("ORACLE_DSN"),
)

cur = conn.cursor()

def run(sql, name):
    try:
        cur.execute(sql)
        print(f"OK: {name}")
    except Exception as e:
        # ORA-00955: name already used (table/index) · ORA-01430: column already in table.
        if "ORA-00955" in str(e) or "ORA-01430" in str(e):
            print(f"Already exists: {name}")
        else:
            print(f"FAILED: {name}")
            raise

run("""
CREATE TABLE papers (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(1000),
    authors CLOB,
    year NUMBER,
    file_path VARCHAR2(2000),
    file_name VARCHAR2(1000),
    file_hash VARCHAR2(128),
    page_count NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
""", "papers")

run("""
CREATE UNIQUE INDEX uq_papers_file_hash ON papers(file_hash)
""", "uq_papers_file_hash")

run("""
CREATE TABLE chunks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paper_id NUMBER NOT NULL,
    section_name VARCHAR2(500),
    chunk_index NUMBER,
    chunk_text CLOB,
    context_text CLOB,
    chunk_type VARCHAR2(100),
    page_start NUMBER,
    page_end NUMBER,
    has_equation NUMBER DEFAULT 0,
    has_algorithm NUMBER DEFAULT 0,
    has_table NUMBER DEFAULT 0,
    audio_concepts CLOB,
    embedding CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chunks_paper FOREIGN KEY (paper_id) REFERENCES papers(id)
)
""", "chunks")

# Upgrade existing databases created before Contextual Retrieval: add context_text.
run("ALTER TABLE chunks ADD (context_text CLOB)", "chunks.context_text")

run("""
CREATE TABLE concepts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(500),
    concept_type VARCHAR2(100),
    description CLOB
)
""", "concepts")

run("""
CREATE TABLE chunk_concepts (
    chunk_id NUMBER,
    concept_id NUMBER,
    relation_type VARCHAR2(100)
)
""", "chunk_concepts")

run("""
CREATE INDEX idx_chunks_paper_id ON chunks(paper_id)
""", "idx_chunks_paper_id")

run("""
CREATE INDEX idx_chunks_section_name ON chunks(section_name)
""", "idx_chunks_section_name")

run("""
CREATE INDEX idx_chunks_chunk_type ON chunks(chunk_type)
""", "idx_chunks_chunk_type")

conn.commit()

cur.execute("SELECT table_name FROM user_tables ORDER BY table_name")
tables = [row[0] for row in cur.fetchall()]

print("\nTables in AUDIO_RAG schema:")
for table in tables:
    print("-", table)

cur.close()
conn.close()

print("\nSchema ready.")